# Generated by Django 4.1.7 on 2023-03-08 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(max_length=500, verbose_name='text content')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_library.category', verbose_name='category')),
            ],
        ),
    ]
