# Generated by Django 4.1.7 on 2023-03-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0007_alter_category_options_remove_videoentry_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoentry',
            name='youtube_id',
            field=models.CharField(default='', max_length=20, verbose_name='youtube id'),
            preserve_default=False,
        ),
    ]
