# Generated by Django 4.1.7 on 2023-04-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0008_videoentry_youtube_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoentry',
            name='youtube_id',
        ),
    ]
