# Generated by Django 4.1.7 on 2023-04-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0010_alter_videoentry_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoentry',
            name='category',
        ),
        migrations.AddField(
            model_name='videoentry',
            name='category',
            field=models.ManyToManyField(to='question_library.category', verbose_name='category'),
        ),
    ]
