# Generated by Django 4.1.7 on 2023-06-12 20:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "question_library",
            "0015_remove_videoentry_url_videoentry_video_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 6, 12, 22, 49, 16, 281327),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
