# Generated by Django 4.1.7 on 2023-05-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0015_auto_20230524_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentry',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Youtube video id'),
        ),
    ]
