# Generated by Django 4.1.7 on 2023-05-25 20:52

from django.db import migrations

from question_library.utils.youtube import extract_video_id_from_url, get_youtube_video_snippet, \
    get_youtube_videos_snippet_list


def fill_video_id_and_title(apps, schema_editor):
    VideoEntry = apps.get_model("question_library", "VideoEntry")
    videos = VideoEntry.objects.all()
    video_id_batch = []
    for video in videos:
        video_id = extract_video_id_from_url(video.url)
        video_id_batch.append(video_id)

    items = get_youtube_videos_snippet_list(video_id_batch)
    for item in items:
        snippet = item["snippet"]
        if not snippet["title"]:
            print(f"Error with video with id {video_id}")
        video = VideoEntry.objects.filter(youtube_id=item["id"]).first()
        if not video:
            print(f"Video not found (id = {item['id']})")
        video.title = snippet['title']
        video.save()


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0016_alter_videoentry_youtube_id'),
    ]

    operations = [
        migrations.RunPython(fill_video_id_and_title)
    ]
