# Generated by Django 4.1.7 on 2023-05-28 09:35

from django.db import migrations

def fill_empty_video_title(apps, schema_editor):
    VideoEntry = apps.get_model("question_library", "VideoEntry")
    videos_empty = VideoEntry.objects.filter(title="")
    for video in videos_empty:
        video.title="[TITLE NOT FOUND]"
        video.save()

class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0017_auto_20230525_2252'),
    ]

    operations = [
        migrations.RunPython(fill_empty_video_title)
    ]
