# Generated by Django 4.1.7 on 2023-05-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0018_auto_20230528_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentry',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='url',
            field=models.CharField(max_length=200, verbose_name='video url'),
        ),
    ]
