# Generated by Django 4.1.7 on 2023-05-29 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('question_library', '0019_alter_videoentry_title_alter_videoentry_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoentry',
            old_name='url',
            new_name='video_url',
        ),
    ]
