# Generated by Django 4.1.7 on 2023-07-03 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0019_rename_yt_duration_videoentry_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoentry",
            name="thumbnail_url",
            field=models.URLField(default="", verbose_name="Video thumblail url"),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 3, 21, 4, 6, 510373),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
