# Generated by Django 4.1.7 on 2023-07-31 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0020_videoentry_thumbnail_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoentry",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Est Visible ?"),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 31, 12, 53, 23, 140830),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
