# Generated by Django 4.1.7 on 2023-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('question_library', '0020_rename_url_videoentry_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='title'),
        ),
    ]
