# Generated by Django 4.1.7 on 2023-07-31 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0023_videoentry_video_embed_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, default="", verbose_name="Video thumblail url"
            ),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 31, 13, 20, 57, 941522),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
