# Generated by Django 4.1.7 on 2023-07-31 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0025_videoentry_author_alter_videoentry_yt_publish_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="video_embed_url",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="video embed url"
            ),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 31, 13, 37, 6, 726005),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
