# Generated by Django 4.1.7 on 2023-07-31 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0026_alter_videoentry_video_embed_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="questions",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="questions"
            ),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 7, 31, 13, 37, 46, 112112),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
