# Generated by Django 4.1.7 on 2023-09-29 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0027_alter_videoentry_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 9, 29, 18, 9, 36, 733474),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
