# Generated by Django 4.1.7 on 2023-10-12 18:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0030_auto_20231010_1658"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="keywords",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Keywords"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 10, 12, 20, 46, 51, 434743),
                verbose_name="Youtube - Video publication date",
            ),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Is active ?"),
                ),
                (
                    "month_questions",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Questions of the month",
                    ),
                ),
                (
                    "day_question",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        null=True,
                        verbose_name="Question of the day",
                    ),
                ),
                (
                    "information_title",
                    models.CharField(
                        blank=True,
                        max_length=180,
                        null=True,
                        verbose_name="Title of the information panel",
                    ),
                ),
                (
                    "information_content",
                    models.TextField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Content of the information panel",
                    ),
                ),
                (
                    "highlighted_video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_library.videoentry",
                        verbose_name="Highlighted video",
                    ),
                ),
                (
                    "month_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question_library.category",
                        verbose_name="Category of the month",
                    ),
                ),
            ],
        ),
    ]
