# Generated by Django 4.1.7 on 2023-10-16 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0032_alter_videoentry_yt_publish_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageInformationCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Is active ?"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=180, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Content"
                    ),
                ),
            ],
            options={
                "verbose_name": "Information Card",
                "verbose_name_plural": "Information Cards",
            },
        ),
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="information_content",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="information_title",
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 10, 16, 15, 46, 47, 517890),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
