# Generated by Django 4.1.7 on 2023-10-16 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0034_homepage_information_cards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 10, 16, 15, 57, 2, 485422),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
