# Generated by Django 4.1.7 on 2023-10-16 14:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0035_alter_videoentry_yt_publish_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageinformationcard",
            name="active",
        ),
        migrations.AddField(
            model_name="homepage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AddField(
            model_name="homepageinformationcard",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Created at",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepageinformationcard",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 10, 16, 16, 3, 41, 659417),
                verbose_name="Youtube - Video publication date",
            ),
        ),
    ]
