# Generated by Django 4.1.7 on 2023-10-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0036_remove_homepageinformationcard_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoentry",
            name="yt_publish_time",
            field=models.DateTimeField(
                blank=True, verbose_name="Youtube - Video publication date"
            ),
        ),
    ]
