# Generated by Django 4.1.7 on 2023-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "question_library",
            "0040_alter_textpost_options_alter_videopost_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="information_cards",
        ),
        migrations.AddField(
            model_name="homepage",
            name="text_posts",
            field=models.ManyToManyField(to="question_library.textpost"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_posts",
            field=models.ManyToManyField(to="question_library.videopost"),
        ),
    ]
