# Generated by Django 4.1.7 on 2023-11-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0042_delete_homepageinformationcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="text_posts",
            field=models.ManyToManyField(blank=True, to="question_library.textpost"),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="video_posts",
            field=models.ManyToManyField(blank=True, to="question_library.videopost"),
        ),
    ]
