# Generated by Django 4.1.7 on 2023-11-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0044_videopost_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoentry",
            name="yt_channel_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Youtube - Channel id",
            ),
        ),
    ]
