# Generated by Django 4.2 on 2023-12-10 15:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0045_videoentry_yt_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, verbose_name='Full name')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
            ],
        ),
    ]
