# Generated by Django 4.2 on 2024-02-17 13:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0047_alter_textpost_content_alter_videopost_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoentry',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='identifier',
            field=models.CharField(default='', max_length=80, verbose_name='Identifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='full_name',
            field=models.CharField(help_text='The full name as displayed on the site', max_length=50, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='This is the indentifier of the category', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='highlighted_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question_library.videoentry', verbose_name='Highlighted video'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='month_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='question_library.category', verbose_name='Category of the month'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='language',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='questions',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, verbose_name='Questions'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='video_embed_url',
            field=models.URLField(blank=True, default='', verbose_name='Embed url'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='video_url',
            field=models.URLField(verbose_name='Video url'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='videoentry',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Is visible ?'),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='full_name',
            field=models.CharField(max_length=20, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='videotype',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Name'),
        ),
    ]
