# Generated by Django 4.2 on 2024-02-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0048_alter_videoentry_options_homepage_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoentry',
            name='yt_publish_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Youtube - Video publication date'),
        ),
    ]
