# Generated by Django 4.2.10 on 2024-03-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0049_alter_videoentry_yt_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.SlugField(help_text='This is the indentifier of the category', unique=True, verbose_name='Name'),
        ),
    ]
