# Generated by Django 4.2.10 on 2024-03-02 17:22

from django.db import migrations

from question_library.utils.common import to_snake_case


def slugify_category_names(apps, schema_editor):
    Category = apps.get_model("question_library", "Category")
    for cat in Category.objects.all():
        cat.name = to_snake_case(cat.name)
        cat.save()

class Migration(migrations.Migration):
    dependencies = [
        ("question_library", "0050_alter_category_name"),
    ]

    operations = [migrations.RunPython(slugify_category_names)]
