# Generated by Django 4.2.10 on 2024-03-06 14:28

from django.db import migrations


def migrate_category_videos_to_ordered_videos(apps, schema_editor):
    Category = apps.get_model("question_library", "Category")
    for cat in Category.objects.all():
        for video in cat.video_entries.all():
            cat.ordered_videos.add(video, through_defaults={"position": 0})


class Migration(migrations.Migration):
    dependencies = [
        (
            "question_library",
            "0052_videoentrywithposition_category_ordered_videos_squashed_0054_alter_videoentrywithposition_position",
        ),
    ]

    operations = [migrations.RunPython(migrate_category_videos_to_ordered_videos)]
