# Generated by Django 4.2.10 on 2024-03-13 22:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [('question_library', '0056_post_orderedpost_homepage_ordered_posts'), ('question_library', '0057_alter_post_options_rename_text_content_post_content'), ('question_library', '0058_alter_post_video'), ('question_library', '0059_alter_post_video'), ('question_library', '0060_alter_post_content')]

    dependencies = [
        ('question_library', '0055_auto_20240306_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active ?')),
                ('header_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Header - Title')),
                ('header_supplementary_information', models.CharField(blank=True, max_length=50, null=True, verbose_name='Header - Supplementary information')),
                ('footer_left_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Footer - Left name')),
                ('footer_left_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Footer - Left value')),
                ('footer_right_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Footer - Right name')),
                ('footer_right_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Footer - Right value')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Content')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_library.videoentry')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='OrderedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_library.homepage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_library.post')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='ordered_posts',
            field=models.ManyToManyField(through='question_library.OrderedPost', to='question_library.post'),
        ),
    ]
