# Generated by Django 4.2.10 on 2024-03-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_library', '0063_alter_homepage_ordered_posts_squashed_0067_alter_postwithposition_home_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='highlighted_video',
        ),
    ]
